dist: bionic
language: Rust

cache:
  cargo: true
  directories:
  - $HOME/.cargo/bin

git:
  depth: false

os:
- osx
- linux

rust:
- stable
- nightly

env:
  global:
  - RUST_BACKTRACE=1
  - PATH="$HOME/.cargo/bin:$PATH"

before_install:
- ci/travis/setup.sh

script:
- ci/travis/script.sh

after_script:
- curl -SsL "https://codecov.io/bash" | bash

before_cache:
- cargo cache -a

deploy:
  provider: script
  script: ci/travis/deploy.sh
  on:
    tags: true
    repo: althonos/cksfv.rs
    rust: stable
    os: linux

notifications:
  email:
  - althonosdev@gmail.com
