[package]
name = "cksfv"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@ens-paris-saclay.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"
chrono = "*"

[dependencies.crc32fast]
version = "*"

[dependencies.memmap]
version = "*"
optional = true

[features]
mmap = ["memmap"]
nightly = ["crc32fast/nightly"]
default-features = []
